version: '2'

services:
  iapweb:
    build: .
    image: iapweb
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    restart: unless-stopped
